DROP TABLE PERSON_GROUP;
DROP TABLE TIME_DEPOSIT_ACCOUNT;
DROP TABLE CHECKING_ACCOUNT;
DROP TABLE MONEY_MARKET_ACCOUNT;
DROP TABLE TRANSACTIONS;
DROP TABLE ACCOUNT;
DROP TABLE GROUPS;
DROP TABLE PERSON;
DROP SEQUENCE PERSON_SEQ RESTRICT;
DROP SEQUENCE ACCOUNT_SEQ RESTRICT;

Create sequence PERSON_SEQ start with 1000;
Create sequence ACCOUNT_SEQ start with 1000;

CREATE TABLE GROUPS(
GROUP_NAME VARCHAR(20) NOT NULL,
GROUP_DESC VARCHAR(200) DEFAULT NULL, 
PRIMARY KEY(GROUP_NAME)
);

CREATE TABLE PERSON(
PERSON_ID INTEGER NOT NULL UNIQUE,
EMAIL VARCHAR(100) NOT NULL,
FIRST_NAME VARCHAR(30) DEFAULT NULL,
LAST_NAME VARCHAR(40) DEFAULT NULL,
USER_PASSWORD VARCHAR(150) NOT NULL,
PRIMARY KEY(EMAIL)
);

CREATE TABLE ACCOUNT(
ACCOUNT_ID INTEGER NOT NULL,
DTYPE VARCHAR(30),
AMOUNT INTEGER,
OWNER INTEGER REFERENCES PERSON(PERSON_ID),
PRIMARY KEY(ACCOUNT_ID)
);

CREATE TABLE TRANSACTIONS(
TRANSACTION_ID INTEGER PRIMARY KEY,
SOURCE_ID INTEGER NOT NULL REFERENCES ACCOUNT(ACCOUNT_ID),
TARGET_ID INTEGER NOT NULL REFERENCES ACCOUNT(ACCOUNT_ID),
TRANSACTIONS_DATE DATE,
AMMOUNT_CHANGE INTEGER, 
INFO VARCHAR(100)
);


CREATE TABLE TIME_DEPOSIT_ACCOUNT(
ACCOUNT_ID INTEGER PRIMARY KEY REFERENCES ACCOUNT(ACCOUNT_ID),
EXPIRE_DATE DATE NOT NULL

);

CREATE TABLE CHECKING_ACCOUNT(
ACCOUNT_ID INTEGER PRIMARY KEY REFERENCES ACCOUNT(ACCOUNT_ID)
);

CREATE TABLE MONEY_MARKET_ACCOUNT(
ACCOUNT_ID INTEGER PRIMARY KEY REFERENCES ACCOUNT(ACCOUNT_ID)
);

CREATE TABLE PERSON_GROUP(
EMAIL VARCHAR(100) NOT NULL,
GROUP_NAME VARCHAR(20) NOT NULL,
PRIMARY KEY(EMAIL,GROUP_NAME),
FOREIGN KEY(EMAIL) REFERENCES PERSON(EMAIL),
FOREIGN KEY (GROUP_NAME) REFERENCES GROUPS(GROUP_NAME)
);
